site_name: STEP-FWD
site_url: https://step-fwd.github.io/STEP-FWD/
docs_dir: ../protocols
markdown_extensions:
- tables
theme:
  name: material
nav:
- Home: index.md
- Technique Protocols:
  - EBL - Raith Elphy Plus using single-layer PMMA: techniques/ebl-raith-elphy-plus-pmma/tabular_protocol.md
